import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {parseCookies} from "nookies";
import {redirectUser} from "../utils/auth";
import MyApp from "./_app";
import {useAuth} from "../context/AuthContext";
import {useRouter} from "next/router";
import {Button} from "antd";
import * as React from "react";

function Home() {
  const { token, logout } = useAuth()
  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome</h1>
        <p className={styles.description}>Your are signup successfull</p>
        <Button danger onClick={() => logout()}>
          logout
        </Button>


      </main>

    </div>
  )
}

Home.getInitialProps = async (ctx) => {
  const { token } = parseCookies(ctx)
  if (!token) redirectUser(ctx, "/signup")
  return { token }
}
export default Home